---
title: "Conditional Variational Autoencoder"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### 1. Import libraries

```{r message=FALSE, warning=FALSE}
# With TF-2, you can still run this code due to the following line:
if (tensorflow::tf$executing_eagerly())
  tensorflow::tf$compat$v1$disable_eager_execution()

library(keras)
K <- keras::backend()

#library(keras)
library(tidyverse)
library(imager)
library(recolorize)
library(OpenImageR)
library(readxl)
```

##### 2. Import dataset

```{r}
files_train <- list.files("Dataset/Images/Train_filtered",  full.names = TRUE, pattern = ".jpg", all.files = TRUE)
#files_train_labels <- list.files("Dataset/Features/Features_Class_Train/",  full.names = TRUE, pattern = ".txt", all.files = TRUE)
labels_train <- read_excel('Dataset/Features/Features_Dummy_Train/Labels_Dummy.xlsx')

files_test <- list.files("Dataset/Images/Test_filtered",  full.names = TRUE, pattern = ".jpg", all.files = TRUE)
#files_test_labels <- list.files("Dataset/Features/Features_Class_Test/",  full.names = TRUE, pattern = ".txt", all.files = TRUE)
labels_test <- read_excel('Dataset/Features/Features_Dummy_Test/Labels_Dummy_test.xlsx')

```

##### 3.Data preprocessing 

**a) Training data**

* **IMAGES**

######  Resize images and assign to a list 
```{r}
Results_train <- list()
for(i in seq_along(files_train)){
  Image <- readImage(files_train[i]) 
  Resized <- resizeImage(Image, width = 24, height = 32) #uniform size of images
  Results_train[[i]] <- Resized
}
```


#Check the number of dimensions
dim(Results_train[[2]])
# 240(height-row) x 320(width-column) x 3(channels - RGB) 


#show images
imageShow(Results_train[[300]])

# Convert list of images into arrays
#train_array <- array()
#for (i in 1:length(Results_train)){
#train_array[i] <- image_to_array(Results_train[[i]], data_format = "channels_last")
#}

train_array <- array(unlist(Results_train), dim=c(1265,24,32,3))
dim(train_array)


dim(train_array)
print(train_array[1])

* **FEATURES**

###### Convert labels into a Dummy (with or without the object). Filter only the detection of pedestrians. 

```{r}
#labels_train$X.person. <- as.integer(labels_train$X.person.)

y_t <- data.frame(labels_train[-c(1:3)]) %>% 
  as.matrix()
```

>**Note**: fasfasfo+sakfoasfkaspofaskpofaskposakfsap

#Use all the labels in the image. 

#labels_train$X.car. <- as.integer(labels_train$X.car.)
#labels_train$X.bus. <- as.integer(labels_train$X.bus.)
#labels_train$X.truck. <- as.integer(labels_train$X.truck.)

###### Convert feature into dummy. 
```{r}
y_train <- to_categorical(y_t, num_classes = NULL, dtype="float32")
```

###### 
